services:
  spoilbuster:
    build:
      context: ../
      dockerfile: ./.devcontainer/dev.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/workspaces/NaviModerator:cached
    environment:
      - PYTHONPATH=/workspaces/NaviModerator/src