services:
  navimoderator:
    build:
      context: ../
      dockerfile: ./.devcontainer/dev.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/workspaces/navimoderator:cached
    environment:
      - PYTHONPATH=/workspaces/navimoderator/src