services:
  navimoderator-chat-monitoring:
    build:
      context: ../
      dockerfile: ./.devcontainer/dev.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/workspaces/navimoderator-chat-monitoring:cached
    environment:
      - PYTHONPATH=/workspaces/navimoderator-chat-monitoring/src